name: ci

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        env:
          REPO_NAME: ${{ github.event.repository.name }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          REPO_NAME_LOWERCASE=$(echo "$REPO_NAME" | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME="$DOCKER_USERNAME/$REPO_NAME_LOWERCASE:latest"
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME